name: Load env
description: Load .env variables and control workflow execution.
inputs:
  enable-workflow:
    description: Name of env var that must be set to 'true' to run.
    required: true
outputs:
  skip:
    description: Whether to skip remaining steps.
    value: ${{ steps.load.outputs.skip }}
runs:
  using: composite
  steps:
    - id: load
      shell: bash
      run: |
        if [ -f .env ]; then
          while IFS='=' read -r key value; do
            if [[ -z "$key" || "$key" == \#* ]]; then
              continue
            fi
            if [ -z "${!key}" ]; then
              echo "$key=$value" >> "$GITHUB_ENV"
              export "$key=$value"
            fi
          done < .env
        fi
        enable_var="${{ inputs.enable-workflow }}"
        if [ "${DISABLE_ALL_WORKFLOWS}" = "true" ] || [ "${!enable_var}" != "true" ]; then
          echo "skip=true" >> "$GITHUB_OUTPUT"
        fi
