name: Document summary
description: Summarize Markdown documents into three bullet points.
model: openai/4o
modelParameters:
  temperature: 0
messages:
  - role: system
    content: |-
      You analyze Markdown documents and return a short summary.
  - role: user
    content: |-
      Summarize the following document in three bullet points.
