repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["--severity-level", "high"]
        exclude: ^tests/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        files: "\\.py$"
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: "\\.py$"
