[project]
name = "doc-ai-analysis-starter"
version = "0.1.0"
description = "Template repository for AI-powered document analysis."
requires-python = ">=3.10"
dependencies = [
    "docling",
    "openai",
    "pydantic",
    "pyyaml",
    "requests",
    "anyio",
    "python-dotenv",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["docai", "docai.*"]
