[project]
name = "github-janitor"
description = "Template repository for AI-powered document analysis."
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "GitHub Janitor", email = "janitor@example.com"}]
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = [
    "docling",
    "openai==1.102.0",
    "httpx",
    "pydantic",
    "pyyaml",
    "requests",
    "anyio",
    "python-dotenv",
    "typer",
    "rich",
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/github-janitor/github-janitor"
Repository = "https://github.com/github-janitor/github-janitor"
Issues = "https://github.com/github-janitor/github-janitor/issues"

[project.scripts]
"doc-ai" = "doc_ai.cli:app"

[project.optional-dependencies]
dev = ["ruff", "pytest"]

[tool.setuptools.package-data]
"doc_ai" = ["py.typed"]

[tool.ruff]
[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E501"]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]

[build-system]
requires = ["setuptools>=61", "wheel", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "doc_ai/_version.py"

[tool.setuptools.packages.find]
include = ["doc_ai", "doc_ai.*"]
