name: AI PR Review
on:
  pull_request:
  issue_comment:
jobs:
  review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.x"}
      - run: pip install openai pyyaml
      - name: Summarize PR
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: python scripts/review_pr.py
  auto-merge:
    if: >
      github.event_name == 'issue_comment' &&
      startsWith(github.event.comment.body, '/merge')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.x"}
      - run: python scripts/merge_pr.py ${{ github.event.issue.number }} --user "${{ github.event.comment.user.login }}"
