name: Prompt Analysis
on:
  workflow_dispatch:
  push:
    paths: ["data/**/*.md"]
jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        prompt: [annual-report, sec-8k, insider-trades]
    steps:
      - name: Load env
        id: env
        run: |
          if [ -f .env ]; then
            while IFS='=' read -r key value; do
              if [[ -z "$key" || "$key" == \#* ]]; then
                continue
              fi
              if [ -z "${!key}" ]; then
                echo "$key=$value" >> $GITHUB_ENV
                export "$key=$value"
              fi
            done < .env
          fi
          if [ "${DISABLE_ALL_WORKFLOWS}" = "true" ] || [ "${ENABLE_PROMPT_ANALYSIS_WORKFLOW}" != "true" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        if: steps.env.outputs.skip != 'true'
      - uses: actions/setup-python@v5
        if: steps.env.outputs.skip != 'true'
        with: {python-version: "3.x"}
      - run: pip install openai pyyaml
        if: steps.env.outputs.skip != 'true'
      - run: |
          for md in data/**/*.md; do
            python scripts/run_prompt.py prompts/${{ matrix.prompt }}.prompt.yaml "$md"
          done
        if: steps.env.outputs.skip != 'true'
      - uses: actions/upload-artifact@v4
        if: steps.env.outputs.skip != 'true'
        with:
          name: ${{ matrix.prompt }}-results
          path: data/**/*.${{ matrix.prompt }}.json
