name: Auto Merge
on:
  issue_comment:
jobs:
  auto-merge:
    if: startsWith(github.event.comment.body, '/merge')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.x'}
      - run: python scripts/merge_pr.py ${{ github.event.issue.number }}
