name: Auto Merge
on:
  issue_comment:
jobs:
  auto-merge:
    if: startsWith(github.event.comment.body, '/merge')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - run: gh pr merge ${{ github.event.issue.number }} --merge
