name: Convert
on:
  push:
    paths: ["data/raw/**"]
jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Load env
        id: env
        run: |
          if [ -f .env ]; then
            while IFS='=' read -r key value; do
              if [[ -z "$key" || "$key" == \#* ]]; then
                continue
              fi
              if [ -z "${!key}" ]; then
                echo "$key=$value" >> $GITHUB_ENV
                export "$key=$value"
              fi
            done < .env
          fi
          if [ "${DISABLE_AUTO_WORKFLOWS}" = "true" ] || [ "${DISABLE_CONVERT_WORKFLOW}" = "true" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        if: steps.env.outputs.skip != 'true'
      - uses: actions/setup-python@v5
        if: steps.env.outputs.skip != 'true'
        with: {python-version: "3.x"}
      - run: pip install docling
        if: steps.env.outputs.skip != 'true'
      - run: python scripts/convert_to_markdown.py data/raw --outdir data/markdown
        if: steps.env.outputs.skip != 'true'
      - name: Commit conversions
        if: steps.env.outputs.skip != 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/markdown/**/*.md
          git commit -m "docs: auto-convert to Markdown" || echo "No changes"
          git push
