name: Docs
on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'docusaurus.config.js'
      - 'sidebars.js'
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Load env
        id: env
        run: |
          if [ -f .env ]; then
            while IFS='=' read -r key value; do
              if [[ -z "$key" || "$key" == \#* ]]; then
                continue
              fi
              if [ -z "${!key}" ]; then
                echo "$key=$value" >> $GITHUB_ENV
                export "$key=$value"
              fi
            done < .env
          fi
          if [ "${DISABLE_ALL_WORKFLOWS}" = "true" ] || [ "${ENABLE_DOCS_WORKFLOW}" != "true" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        if: steps.env.outputs.skip != 'true'
      - uses: actions/setup-node@v4
        if: steps.env.outputs.skip != 'true'
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
        if: steps.env.outputs.skip != 'true'
      - run: npm run build
        if: steps.env.outputs.skip != 'true'
      - uses: actions/upload-pages-artifact@v1
        if: steps.env.outputs.skip != 'true'
        with:
          path: build
      - id: deployment
        if: steps.env.outputs.skip != 'true'
        uses: actions/deploy-pages@v2
