name: Lint
on:
  push:
    paths: ["**/*.py", "pyproject.toml"]
  pull_request:
    paths: ["**/*.py", "pyproject.toml"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Load env
        id: env
        uses: ./.github/actions/load-env
        with:
          enable-workflow: ENABLE_LINT_WORKFLOW
      - uses: actions/checkout@v4
        if: steps.env.outputs.skip != 'true'
      - uses: actions/setup-python@v5
        if: steps.env.outputs.skip != 'true'
        with: {python-version: "3.x"}
      - run: pip install ruff
        if: steps.env.outputs.skip != 'true'
      - run: ruff check .
        if: steps.env.outputs.skip != 'true'
