name: Lint
on:
  push:
    paths: ["**/*.py", "pyproject.toml"]
  pull_request:
    paths: ["**/*.py", "pyproject.toml"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Load env
        id: env
        run: |
          if [ -f .env ]; then
            while IFS='=' read -r key value; do
              if [[ -z "$key" || "$key" == \#* ]]; then
                continue
              fi
              if [ -z "${!key}" ]; then
                echo "$key=$value" >> $GITHUB_ENV
                export "$key=$value"
              fi
            done < .env
          fi
          if [ "${DISABLE_ALL_WORKFLOWS}" = "true" ] || [ "${ENABLE_LINT_WORKFLOW}" != "true" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        if: steps.env.outputs.skip != 'true'
      - uses: actions/setup-python@v5
        if: steps.env.outputs.skip != 'true'
        with: {python-version: "3.x"}
      - run: pip install ruff
        if: steps.env.outputs.skip != 'true'
      - run: ruff check .
        if: steps.env.outputs.skip != 'true'
