name: PR Review
on:
  pull_request:
  workflow_dispatch:
    inputs:
      model:
        description: Model name to use
        required: false
        default: gpt-4.1
jobs:
  review:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Load env
        id: env
        uses: ./.github/actions/load-env
        with:
          enable-workflow: ENABLE_PR_REVIEW_WORKFLOW
      - name: Setup Python
        if: steps.env.outputs.skip != 'true'
        uses: ./.github/actions/setup-python
        with:
          packages: openai pyyaml
      - name: Review PR
        if: steps.env.outputs.skip != 'true'
        id: review
        env:
          MODEL: ${{ github.event.inputs.model || env.PR_REVIEW_MODEL || 'gpt-4.1' }}
        uses: ./.github/actions/review-pr
        with:
          prompt: prompts/pr-review.prompt.yaml
          body: ${{ github.event.pull_request.body }}
          model: ${{ env.MODEL }}
          output-file: pr-review.txt
      - name: Comment on PR
        if: steps.env.outputs.skip != 'true'
        uses: ./.github/actions/comment-pr
        with:
          body-file: pr-review.txt
