name: PR Review
on:
  pull_request:
  workflow_dispatch:
    inputs:
      model:
        description: Model name to use
        required: false
        default: gpt-4.1
jobs:
  review:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Load env
        id: env
        run: |
          if [ -f .env ]; then
            while IFS='=' read -r key value; do
              if [[ -z "$key" || "$key" == \#* ]]; then
                continue
              fi
              if [ -z "${!key}" ]; then
                echo "$key=$value" >> $GITHUB_ENV
                export "$key=$value"
              fi
            done < .env
          fi
          if [ "${DISABLE_ALL_WORKFLOWS}" = "true" ] || [ "${ENABLE_PR_REVIEW_WORKFLOW}" != "true" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        if: steps.env.outputs.skip != 'true'
      - uses: actions/setup-python@v5
        if: steps.env.outputs.skip != 'true'
        with: {python-version: "3.x"}
      - run: pip install openai pyyaml
        if: steps.env.outputs.skip != 'true'
      - name: Review PR
        if: steps.env.outputs.skip != 'true'
        id: review
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          MODEL: ${{ github.event.inputs.model || env.PR_REVIEW_MODEL || 'gpt-4.1' }}
        run: |
          python scripts/review_pr.py prompts/pr-review.prompt.yaml "$PR_BODY" --model "$MODEL" | tee pr-review.txt
      - name: Comment on PR
        if: steps.env.outputs.skip != 'true'
        run: |
          body=$(cat pr-review.txt)
          gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments -f body="$body"
