name: PR Review
on:
  pull_request:
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Load env
        id: env
        run: |
          if [ -f .env ]; then
            cat .env >> $GITHUB_ENV
          fi
          if [ "${DISABLE_AUTO_WORKFLOWS}" = "true" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        if: steps.env.outputs.skip != 'true'
      - uses: actions/setup-python@v5
        if: steps.env.outputs.skip != 'true'
        with: {python-version: "3.x"}
      - run: pip install openai pyyaml
        if: steps.env.outputs.skip != 'true'
      - name: Review PR
        if: steps.env.outputs.skip != 'true'
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          python scripts/review_pr.py prompts/pr-review.prompt.yaml "$PR_BODY"
