name: Review Comment
on:
  issue_comment:
jobs:
  review:
    if: startsWith(github.event.comment.body, '/review')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install openai pyyaml
      - name: AI Review
        env:
          PR_BODY: ${{ github.event.issue.body }}
        run: |
          summary=$(python scripts/review_pr.py --pr-body "$PR_BODY")
          gh issue comment ${{ github.event.issue.number }} --body "$summary"
