name: Validate Conversions
on:
  push:
    paths:
      - "data/**/*.md"
      - "data/**/*.html"
      - "data/**/*.json"
      - "data/**/*.txt"
      - "data/**/*.doctags"
jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Load env
        id: env
        uses: ./.github/actions/load-env
        with:
          enable-workflow: ENABLE_VALIDATE_WORKFLOW
      - uses: actions/checkout@v4
        if: steps.env.outputs.skip != 'true'
      - uses: actions/setup-python@v5
        if: steps.env.outputs.skip != 'true'
        with: {python-version: "3.x"}
      - run: pip install docling openai pyyaml
        if: steps.env.outputs.skip != 'true'
      - run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'data/**/*.md' 'data/**/*.html' 'data/**/*.json' 'data/**/*.txt' 'data/**/*.doctags'); do
            raw=${file%.*}.pdf
            fmt=${file##*.}
            python scripts/validate.py $raw $file --prompt prompts/validate-output.prompt.yaml || (
              git checkout -- $file
              python scripts/convert.py $raw --format $fmt
              git add $file
            )
          done
        if: steps.env.outputs.skip != 'true'
      - name: Commit validation metadata
        if: steps.env.outputs.skip != 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          find data -name '*.dc.json' -print0 | xargs -0 git add
          git commit -m "chore: update validation metadata" || echo "No changes"
          git push
      - name: Create PR if fixes
        if: steps.env.outputs.skip != 'true'
        run: |
          git diff --staged --quiet && exit 0
          branch="fix-conversion-$(date +%s)"
          git checkout -b "$branch"
          git commit -m "docs: fix document conversion"
          git push origin "$branch"
          gh pr create --fill --title "Fix document conversion" --body "Auto-corrected mismatched output."
